ansible_manager/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include('forms.urls')),
    path('admin/', admin.site.urls),
    # path('register-users',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
            ),
            name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
            ),
            name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
            ),
            name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
            ),
            name='password_reset_complete'),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

forms/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.dashboard,name='dashboard'),
    path('launch_vm_request',views.launch_vm_request,name='vm_request'),
    path('launch_vm_request/new_vm',views.new_vm, name='new_vm'),
    path('manage_vm/power_on',views.power_on, name='power_on'),
    path('manage_vm/power_off',views.power_off, name='power_off'),
    path('manage_vm/restart',views.restart, name='restart'),
    path('manage_vm/user_add',views.user_add,name='user_add'),
    path('manage_vm/user_remove',views.user_remove,name='user_remove'),
    path('manage_vm/create_dir',views.create_dir,name='create_dir'),
    path('manage_vm/delete_dir',views.delete_dir,name='delete_dir'),
    path('open-exercise/<int:exercise_id>/',views.open_pdf,name='open-exercise'),
    path('crypt_request_form',views.crypt,name='crypt'),
    path('crypt_request',views.crypt_request,name='crypt_request'),
    path('download_csv/<int:request_id>',views.download_csv,name="download_csv")
]

forms/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.db.models.signals import pre_delete
import os

# Create your models here.

def validate_pdf_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError('Only Pdf files are allowed.')

class Exercise(models.Model):
    name=models.CharField(max_length=200)
    description=models.TextField(null=True)
    pdf_file=models.FileField(upload_to='exercises/',validators=[validate_pdf_extension])

    def __str__(self):
        return self.name

@receiver(pre_delete, sender=Exercise)
def delete_pdf_file(sender,instance,**kwargs):
    if instance.pdf_file:
        if os.path.isfile(instance.pdf_file.path):
            os.remove(instance.pdf_file.path)

pre_delete.connect(delete_pdf_file,sender=Exercise)

class VMRequest(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    course_number=models.CharField(max_length=200, null=True)
    course_name=models.CharField(max_length=200)
    instructor_name=models.CharField(max_length=200)
    ta_name=models.CharField(max_length=200, null=True)
    description=models.TextField(null=True)
    semester=models.CharField(max_length=200)
    year=models.PositiveSmallIntegerField()
    os=models.CharField(max_length=200)
    cpu_count=models.PositiveSmallIntegerField(null=True)
    ram=models.PositiveSmallIntegerField(null=True)
    ram_reason=models.TextField(null=True)
    hard_disk=models.PositiveSmallIntegerField(null=True)
    disk_reason=models.TextField(null=True)
    num_vm=models.PositiveSmallIntegerField()
    start_date=models.CharField(max_length=200, null=True)
    end_date=models.CharField(max_length=200, null=True)
    self_sudo=models.CharField(max_length=200, null=True)
    vm_users=models.TextField(null=True)
    network=models.CharField(max_length=200, null=True)
    vm_user_file=models.FileField(upload_to='vm_users/', null=True)
    status=models.CharField(max_length=200, null=True)

class VM(models.Model):
    vmrequest=models.ForeignKey(VMRequest,on_delete=models.CASCADE, null=True,blank=True)
    ip_addr=models.CharField(max_length=200)
    vm_name=models.CharField(max_length=200)
    folder_name=models.CharField(max_length=200, null=True)
    os=models.CharField(max_length=200)
    template=models.CharField(max_length=200, null=True)

class CryptRequest(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    technique=models.CharField(max_length=200)
    random_key=models.CharField(max_length=200)
    key=models.CharField(max_length=300,null=True)
    num_cipher=models.PositiveSmallIntegerField(null=True)
    ip_address_list=models.TextField(null=True)

class CryptText(models.Model):
    cryptreq=models.ForeignKey(CryptRequest,on_delete=models.CASCADE)
    plaintext=models.TextField()
    ciphertext=models.TextField()
    key=models.TextField()
    ip_addr=models.CharField(max_length=200, null=True)


    


        

forms/admin.py
from django.contrib import admin
from .models import Exercise
from .models import VMRequest
from .models import VM
from .models import CryptRequest,CryptText
# Register your models here.

admin.site.register(Exercise)
admin.site.register(VMRequest)
admin.site.register(VM)
admin.site.register(CryptRequest)
admin.site.register(CryptText)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.template import loader
from django.shortcuts import redirect, get_object_or_404
from django.templatetags.static import static
from django.conf import settings
import os
from ansible_runner import run
import json
import pandas as pd
import random
from django.contrib.auth.decorators import login_required
from .models import Exercise,VM,VMRequest,CryptRequest,CryptText
from dotenv import load_dotenv
import csv
import yaml

load_dotenv()
# Create your views here.

become_password=os.environ.get('BECOME_PASSWORD')
static=settings.STATIC_ROOT

template_path=static+'/forms/playbooks/template.yml'

Vlan_3072=static+'/IP_RANGE_3072.txt'
Vlan_4093=static+'/IP_RANGE_4093.txt'

NETWORK={
    '1':'Vlan_3072',
    '2':'Vlan_4093',
    '3':'Both'
}

with open(template_path,"r") as yaml_file:
    VM_TEMPLATES=yaml.safe_load(yaml_file)

inventory_path=static+'/forms/playbooks/inventory'
vault_password_cmd='--vault-password-file '+static+'/forms/playbooks/pass.txt'
ssh_key_path=static+'/forms/playbooks/ansible'

with open(ssh_key_path,'r') as key_file:
    private_key_file=key_file.read()

def get_available_ips(network):
    with open(network,'r') as file:
        ip_list=[line.strip() for line in file]
    return ip_list

def assign_ips(num_ips_to_assign,network):
    available_ips=get_available_ips(network)
    num_available_ips=len(available_ips)

    if num_ips_to_assign>num_available_ips:
        return []
    
    assigned_ips=[]

    for _ in range(num_ips_to_assign):
        random_index=random.randint(0,num_available_ips-1)
        available_ips[random_index],available_ips[-1]=available_ips[-1],available_ips[random_index]
        assigned_ips.append(available_ips.pop())
        num_available_ips-=1

    with open(network,"w") as file:
        file.write('\n'.join(available_ips))
    return assigned_ips

    
def dashboard(request):
    exercises=Exercise.objects.all()
    return render(request,'forms/main.html',{'exercises':exercises})

@login_required
def launch_vm_request(request):
    user=request.user
    vm_requests=VMRequest.objects.filter(user=user)
    return render(request,'forms/vm_request.html',{'vm_requests':vm_requests})

    
@login_required
def vm_csv(request, request_id):
    response=HttpResponse(content_type='text_csv')
    response['Content-Disposition']='attachment; filename="ciphertexts.csv"'

    writer=csv.writer(response)
    writer.writerow(['Plaintext','Ciphertext','Key','IP Address'])

    ciphertexts=CryptText.objects.filter(cryptreq=request_id)

    for cipertext in ciphertexts:
        writer.writerow([cipertext.plaintext,cipertext.ciphertext,cipertext.key,cipertext.ip_addr])
    
    return response

@login_required
def new_vm(request):
    if request.method=='POST':
    
        course_number=request.POST['course_number']
        course_name=request.POST['course_name']
        instructor_name=request.POST['instructor_name']
        desc=request.POST['description']
        ta_name=request.POST['ta_name']
        sem=request.POST['sem']
        year=request.POST['year']
        os=request.POST['os']
        cpu=request.POST['num_cpu']
        ram=request.POST['ram']
        ram=int(ram)*1024
        extra_ram=request.POST['extra_ram']
        hard_disk=request.POST['conf']
        num_vm=request.POST['num_vm']
        network=request.POST['network']
        user=request.user

        vm_req=VMRequest(user=user,course_number=course_number,course_name=course_name,instructor_name=instructor_name, ta_name=ta_name,description=desc, semester=sem, year=year, os=os, cpu_count=cpu, ram=ram, network=NETWORK[network], ram_reason=extra_ram, hard_disk=hard_disk, num_vm=num_vm)
        vm_req.save()
        req_id=vm_req.id

        folder_name=course_number+instructor_name.split(' ')[0]

        vm_name=[]
        for i in range(int(num_vm)):
            vm_name.append(course_number+instructor_name.split(' ')[0]+'-'+str(req_id)+os+'-'+str(i+1))

        template=VM_TEMPLATES.get(f'{os}-{network}-{hard_disk}',"")

        if template=='':
            return JsonResponse({'success':False,'message':"Sorry, currently the template for your required configuration is not present."})

        if network=='1':
            playbook_path=static+'/forms/playbooks/deploy_template_1.yml'
            ip_address=assign_ips(int(num_vm),Vlan_3072)
            if len(ip_address)==0:
                return JsonResponse({'success':False,'message':"Don't have enough ip_address to allocate"})

            vm_list=[]
            for i in range(int(num_vm)):
                vm_list.append(vm_name[i]+','+ip_address[i]+','+'.'.join(ip_address[i].split('.')[:3])+'.1')

        elif network=='2':
            playbook_path=static+'/forms/playbooks/deploy_template_2.yml'
            ip_address=assign_ips(int(num_vm),Vlan_4093)
            if len(ip_address)==0:
                return JsonResponse({'success':False,'message':"Don't have enough ip_address to allocate"})
            
            vm_list=[]
            for i in range(int(num_vm)):
                vm_list.append(vm_name[i]+','+ip_address[i])

        else:
            playbook_path=static+'/forms/playbooks/deploy_template_3.yml'
            ip_address=assign_ips(int(num_vm),Vlan_3072)
            net2_ip=assign_ips(int(num_vm),Vlan_4093)
            if len(ip_address)==0 or len(net2_ip)==0:
                return JsonResponse({'success':False,'message':"Don't have enough ip_address to allocate"})
            vm_list=[]
            for i in range(int(num_vm)):
                vm_list.append(vm_name[i]+','+ip_address[i]+','+'.'.join(ip_address[i].split('.')[:3])+'.1'+','+net2_ip[i])
        
        vm_list=json.dumps(vm_list)

        extra_vars={
            'create_folder_name':folder_name,
            'create_vm_name':vm_name,
            'create_template':template,
            'num_vm':int(num_vm),
            'cpu': int(cpu),
            'ram':int(ram),
            'vm_list':vm_list,
        }

        options={
            'extravars':extra_vars,
            'cmdline':vault_password_cmd,
            
        }
        result=run(playbook=playbook_path,**options)
        if result.rc==0:
            if network=='3':
                for i in range(int(num_vm)):
                    vms=VM(vmrequest=vm_req,ip_addr=ip_address[i],vm_name=vm_name[i],folder_name=folder_name,os=os,template=template)
                    vms.save()
                
                with open(inventory_path, "r") as inventory_file:
                    existing=inventory_file.read()
            
                ip_address=[f"crange1@{ip}" for ip in ip_address]

                new_ip="\n".join(ip_address)+"\n"+existing
            
                with open(inventory_path, "w") as inventory_file:
                    inventory_file.write(new_ip)
            
                for i in range(int(num_vm)):
                    vms=VM(vmrequest=vm_req,ip_addr=net2_ip[i],vm_name=vm_name[i],folder_name=folder_name,os=os,template=template)
                    vms.save()
            
                ip_address=[f"crange1@{ip}" for ip in net2_ip]

                new_ip="\n".join(ip_address)+"\n"
            
                with open(inventory_path, "a") as inventory_file:
                    inventory_file.write(new_ip)
            elif network=='2':
                for i in range(int(num_vm)):
                    vms=VM(vmrequest=vm_req,ip_addr=ip_address[i],vm_name=vm_name[i],folder_name=folder_name,os=os,template=template)
                    vms.save()
            
                ip_address=[f"crange1@{ip}" for ip in ip_address]

                new_ip="\n".join(ip_address)+"\n"
            
                with open(inventory_path, "a") as inventory_file:
                    inventory_file.write(new_ip)
            else:
                for i in range(int(num_vm)):
                    vms=VM(vmrequest=vm_req,ip_addr=ip_address[i],vm_name=vm_name[i],folder_name=folder_name,os=os,template=template)
                    vms.save()
                
                with open(inventory_path, "r") as inventory_file:
                    existing=inventory_file.read()
            
                ip_address=[f"crange1@{ip}" for ip in ip_address]

                new_ip="\n".join(ip_address)+"\n"+existing
            
                with open(inventory_path, "w") as inventory_file:
                    inventory_file.write(new_ip)
            
            return JsonResponse({'success':True,'message':"VM's created"})
        else:
            return JsonResponse({'success':False,'message':"Something went wrong. VM's couldn't be created"})
    else:
        return render(request,'forms/new_vm_form.html')

@login_required
def power_on(request):
    
    if request.method=='POST':
        playbook_path=static+'/forms/playbooks/power_server.yml'

        if request.POST.get('ip_addr')!='':
            vm_objects=VM.objects.all()
            IP_NAME={}
            folder_name={}
            for vm in vm_objects:
                IP_NAME[vm.ip_addr]=f'{vm.folder_name},{vm.vm_name}'

            ip_addr=[IP_NAME.get(ip.strip()) for ip in request.POST.get('ip_addr').split(',')]
            if None in ip_addr:
                return JsonResponse({'message':"VM Not Found"})
            
            machine_list=json.dumps(ip_addr)
        
        elif request.POST.get('vm_name')!='':
            vms=[vm.strip() for vm in request.POST.get('vm_name').split(',')]
            vm_list=[]
            for vm in vms:
                if len(vm.split('/'))==2:
                    folder,ip=vm.split('/')
                    vm_list.append(folder+','+ip)
                else:
                    return JsonResponse({'success':False,'message':"Folder name not provided properly"})
            
            machine_list=json.dumps(vm_list)

        extra_vars={
            'machine_list':machine_list
        }
        options={

forms/templates/forms/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Virtual Machine Manager</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">  
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" type="text/css" href="{% static 'forms/main.css' %}">
        <!-- <script src="{% static 'forms/main.js' %}" defer></script> -->
        <style>
            .table-responsive{
                margin:30px;
            }
            .block-button{
                text-align: center;
                margin-top: 10px;
                
            }
            .vm_form{
                margin:20px;
            }
            .form-group{
                padding:10px;
            }
            fieldset{
                padding-top:20px;
            }
            .fieldset-heading{
                font-weight: bold;
            }
            label{
                padding-bottom: 5px;;
            }
            .not-visible{
                display:none;
                position:fixed;
                top:0;
                left:0;
                right:0;
                bottom:0;
                width:100%;
                background:rgba(0,0,0,0.75) url('{% static "/forms/loading.gif" %}') no-repeat center center;
                z-index:1000;

            }
            .nav-item{
                margin-left: 20px;
            }
            .ex-info{
                display:flex;
                align-items: center;
            }
            .ex-name{
                margin-right: 10px;
                min-width: 50px;
            }
            .ex-desc{
                margin-left:10px;
                margin-right: 20px;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container d-flex justify-content-between">
                <a class="navbar-brand" href="{% url 'dashboard' %}">Virtual Machine Manager</a>
                <div>
                    <ul class="navbar-nav flex-row">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'login' %}" class="nav-link">Login</a>
                        </li>
                       
                        {% endif %}
                    </ul>
                </div>
            </div>

        </nav>

        
        <div class="main-block">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
        {% block content %}{% endblock %}
    	</div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
        
    </body>
</html>

forms/templates/forms/create_dir.html
{% extends "forms/base.html" %}
{% block content %}  
<div class="container form-container">
    <h1>Create Directory</h1> 
    <div class="vm_form">
        <form action="{% url 'create_dir' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <p class="text-muted">Give List of VM's (ip-addresses) on which the task need to be conducted. 
                            Give Comma Separated List. <br>Eg: 192.121.85.23,192.121.85.24
                        </p>
                        <label for="ip_addr">Machines for directory creation</label>
                        <textarea class="form-control" name="ip_addr" id="ip_addr" required></textarea>
                    
                    </div>
                    <div class="form-group col-md-12">
                        <label for="dir_path">Give list of directory paths to be added</label>
                        <p class="text-muted">Format: directory_path,directory_permission (giving permission is optional)</p>
                        <textarea class="form-control" name="dir_path" id="dir_path" placeholder="/home/bhargavi,0755&#10/home/darshan"></textarea>
                    </div>
                    
                </div>
            </fieldset>
            <div class="block-button"><button type="submit" class="btn btn-primary btn-block">Create</button></div>
        </form>
    </div>
</div>
<div id="loader" class="text-center mt-3 not-visible">
    <div class="spinner-border" role="status"></div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script>
    var spinner=$('#loader');
    $(function(){
        $('form').submit(function(e){
            e.preventDefault();
            var formData=new FormData(this);
            spinner.show();
            $.ajax({
                url:'{% url "create_dir" %}',
                data:formData,
                processData: false,
                contentType:false,
                type:'POST',
                
            }).done(function(response){
                $('#loader').hide();
                alert(response.message);
                if (response.success){
                    window.location.href='{% url "dashboard" %}';
                }
                else{
                    window.location.reload();
                }

            });
        });
    });
</script>
{% endblock content %}

forms/templates/forms/crypt.html
{% extends "forms/base.html" %}
{% block content %}  
<div class="container form-container">
    <h1>Cryptography</h1>
    <div class="vm_form">
        <form action="{% url 'crypt' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <fieldset>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="tech">Select Cryptography Technique</label>
                        <select class='form-select' name="tech" id="tech">
                            <option value="ceaser" selected>Ceaser Cipher</option>
                            <option value="rotation">Rotation Cipher</option>
                            <option value="transposition">Transposition Cipher</option>
                            <option value="vernam">Vernam</option>
                            <option value="vigenere">Vigenere</option>
                        </select>
                    </div>

                    <div class="form-group col-md-12">
                        <label for="random_key">Do you want the key to be random? (For Vernam and Ceaser Cipher Key is not required)</label>
                        <select class='form-select' name="random_key" id="random_key">
                            <option value="yes" selected>Yes</option>
                            <option value="no">No</option>
                        </select>
                    </div>

                    <div class="form-group col-md-12">
                        <label for="key">If no random_key, then please provide a key (except for Ceaser and Vernam). Please don't have space or special characters in keys</label>
                        <input type="text" class="form-control" id="key" name="key" placeholder="" >
                    </div>

                    <div class="form-group col-md-12">
                        <label for="default">Do you want default plaintexts?</label>
                        <select class='form-select' name="default" id="default">
                            <option value="yes" selected>Yes</option>
                            <option value="no">No</option>
                        </select>
                    </div>

                    <div class="form-group col-md-12">
                        <label for="plain">Please give plaintexts separated by a line if don't want to use default.</label>
                        <textarea class="form-control" name="plain" id="plain"></textarea>
                    </div>

                    <div class="form-group col-md-12">
                        <label for="num_cipher">If using default plaintext, give the number of ciphertexts to be generated</label>
                        <input type="number" min="1" max="40" class="form-control" id="num_cipher" name="num_cipher" placeholder="" >
                    </div>

                    <div class="form-group col-md-12">
                        <label for="ip_addr">If you want to copy ciphertext to a machine, please give list of ip_addresses to be copied to. (Give comma-separated list. Eg: 192.181.29.1, 192.81.21.1)</label>
                        <textarea class="form-control" name="ip_addr" id="ip_addr"></textarea>
                    </div>
                    
                </div>
            </fieldset>
           
            <div class="block-button"><button type="submit" class="btn btn-primary btn-block">Create Cipher</button></div>
        </form>
    </div>
</div>
<div id="loader" class="text-center mt-3 not-visible">
    <div class="spinner-border" role="status"></div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script>
    var spinner=$('#loader');
    $(function(){
        $('form').submit(function(e){
            e.preventDefault();
            var formData=new FormData(this);
            spinner.show();
            $.ajax({
                url:'{% url "crypt" %}',
                data:formData,
                processData: false,
                contentType:false,
                type:'POST',
                
            }).done(function(response){
                $('#loader').hide();
                alert(response.message);
                if (response.success){
                    window.location.href='{% url "dashboard" %}';
                }
                else{
                    window.location.reload();
                }

            });
        });
    });
</script>
{% endblock content%}
   

  

forms/templates/forms/crypt_request.html
{% extends "forms/base.html" %}
{% block content %}  
<h1>Cryptography Requests</h1>
<div class="block-button"><a href="{% url 'crypt' %}" class="btn btn-primary btn-lg btn-block">New Ciphertext Request</a>  
</div>
<div class='table-responsive'>
  <table class="table table-striped mytable">
      <thead>
      <tr>
          <th scope="col">Technique</th>
          <th scope="col">Random Key</th>
          <th scope="col">Key</th>
          <th scope="col">Number of Ciphertext</th>
          <th scope="col">Show Cipher</th>
      </tr>
      </thead>
      <tbody>
        {% for request in crypt_requests %}
      <tr>
          <td>{{request.technique}}</td>
          <td>{{request.random_key}}</td>
          <td>{{request.key}}</td>
          <td>{{request.num_cipher}}</td>
          <td><a href="{% url 'download_csv' request.id %}" class="btn btn-primary btn-sm" type="button" >
            Download
          </a></td>
        </tr>
        
     
        {% endfor %}
      </tbody>
  </table>
</div>
{% endblock content%}
 
    
   

  

forms/templates/forms/vm_request.html
{% extends "forms/base.html" %}
{% block content %}  
<h1>VM Requests</h1>
<div class="block-button"><a href="{% url 'new_vm' %}" class="btn btn-primary btn-lg btn-block">New VM Request</a>  
</div>
<div class='table-responsive'>
  <table class="table table-striped mytable">
      <thead>
      <tr>
          <th scope="col">Course Number</th>
          <th scope="col">Course Name</th>
          <th scope="col">Instructor Name</th>
          <th scope="col">TA Name</th>
          <th scope="col">Semester</th>
          <th scope="col">Year</th>
          <th scope="col">Os</th>
          <th scope="col">IP_address</th>
      </tr>
      </thead>
      <tbody>
        {% for request in vm_requests %}
      <tr>
          <td>{{request.course_number}}</td>
          <td>{{request.course_name}}</td>
          <td>{{request.instructor_name}}</td>
          <td>{{request.ta_name}}</td>
          <td>{{request.semester}}</td>
          <td>{{request.year}}</td>
          <td>{{request.os}}</td>
          <td>{% for vm in request.vm_set.all %}
            {{vm.ip_addr}}({{vm.folder_name}}/{{vm.vm_name}}){% if not forloop.last%},{% endif%}
            {% endfor%}
          </td>
        </tr>
        
     
        {% endfor %}
      </tbody>
  </table>
</div>
{% endblock content%}
 
    
   

  